baseURL: "https://waltermays.com/"
title: "Walter Mays"
languageCode: "en-us"
author: "Walter Mays"

theme: "sircular-blog"
paginate: 5

preserveTaxonomyNames: true

pygmentsCodefences: true
pygmentsStyle: "tango"

taxonomies:
  category: "categories"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Learn You Some Linux"
      url: "/learn-you-some-linux/"
      weight: 2
    - name: "Blog"
      url: "/blog/"
      weight: 3

params:
  favicon_url: "/favicon.ico"
  email: "walt@waltermays.com"
  github_username: "Sircular"

permalinks:
  blog: "/blog/:year/:month/:title"

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"
