name = "Sircular Blog"
license = "MIT"
description = "A simple blogging theme."
tags = []
features = []

[author]
name = "Walter Mays"
homepage = "https://waltermays.com/"

[outputFormats]
[[outputFormats.RSS]]
mediatype = "application/rss"
baseName = "feed"
